--- 
title: " Introduction to Probability <br> \\newline First Edition"
author: ""
# Include title and author for HTML/Gitbook output
site: bookdown::bookdown_site
output:
  bookdown::gitbook
documentclass: krantzNoCorner
classoption: krantz2
colorlinks: yes
fontsize: 12pt
bibliography: ["referece2025.bib"]
biblio-style: econPeriod
link-citations: yes
github-repo: https://github.com/openprobabilitytext/introprob
description: "Introduction to Probability is a freely available textbook for MATH350 students.
  -  This version contains variety of examples to learn the probability concepts in your own phase.
  -  The book can be downloaded as a pdf."
---

# Include title and author for HTML/Gitbook output

Placeholder



<!--chapter:end:index.Rmd-->

# Fundamentals of Probability and Its Axioms

## Combinations and Permutations
Counting plays a very important role in probability. In probability, we often deal with sets, and counting methods such as combinations and permutations help us find the number of elements in a set. Specifically, in probability, we deal with a set called the **sample space** which is the set of all possible outcomes of some random experiment and **events**, which are subsets of the sample space. Typically, the sample space is denoted by $S$ or $\Omega.$ Consider the following example:

**Example 1.1.**
Suppose a fair coin is flipped twice.What is the probability of flipping at least one head?


`r HideExample('Example 1.1.', 'Show Example Solution')`

`r SolnBegin()` The sample space of this experiment can expressed as $S=\{HH,HT,TH,TT\}$. Now, consider the event:
$$A=\{\text{At least one outcome is a head}\}$$
Notice that $A\subset S$ ($A$ is a subset of $S$). Since $A=\{HH,HT,TH\},$ we can find the probability as follows:
$$P(A)= \frac{\#\text{elements in A}}{\#\text{elements in S}}=\frac{3}{4}.$$
`r SolnEnd()`

</div>

<!--chapter:end:02-counting.Rmd-->

# Basic Probability

<!--chapter:end:03-basics.Rmd-->




<!--chapter:end:Glossary.Rmd-->


```{r include = FALSE}
library("actuar")
library("alabama")
library("epitools")
library("GB2")
library("pander")
library("VGAM")
library("psych")
library("copula")
library("statmod")

library("tseries")
library("boot")
library("scales")
library("rpart")
library("rpart.plot")
library("RColorBrewer")
library("forecast")
library("splines")
library("MASS")
library("survival")
library("Hmisc")
library("goftest")
library("gifski")
library("invgamma")
#library("ChainLadder")
library("knitr")
library("kableExtra")
options(kableExtra.html.bsTable = FALSE)
library("magick")
library("pdftools")
library("dplyr")
library("GofCens")
library("Metrics")
library("webexercises")

library("invgamma")
library("patchwork")
library("mcmcse")
library('gganimate')
library('transformr')
#library('CASdatasets')
#library('insuranceData')
library('ggplot2')
library("nimble")
library("gridExtra")
library("grid")

# Install as needed

# install.packages("CASdatasets", repos = "http://cas.uqam.ca/pub/", type="source")


```

<!--chapter:end:Packages.Rmd-->




<!--chapter:end:PdfOutput.Rmd-->

